version: '3'

services:
  
  eureka:
    build: ../eureka-server
    image: eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
      
  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbit
     ports:
       - 15672:15672
       - 5672:5672
     labels:
       NAME: rabbitmq
     volumes:
       - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config